#!/usr/bin/env python3
"""
This module contains a coroutine called async_comprehension
that collects 10 random numbers from async_generator.
"""

from typing import List
from 0_async_generator import async_generator

async def async_comprehension() -> List[float]:
    """
    Coroutine that collects 10 random numbers from async_generator.

    This coroutine will use an async comprehension to iterate over
    async_generator and collect 10 random numbers into a list.
    
    Returns:
        List[float]: A list of 10 random numbers generated by async_generator.
    """
    return [number async for number in async_generator()]

